services:
  postgresql:
    image: postgres:17
    container_name: postgresql
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: User
    volumes:
      - ./data/user:/var/lib/postgresql/data
    networks:
      - my_network

  postgresql2:
    image: postgres:17
    container_name: postgresql2
    ports:
      - "5435:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Blog
    volumes:
      - ./data/blog:/var/lib/postgresql/data
    networks:
      - my_network

  postgresql3:
    image: postgres:17
    container_name: postgresql3
    ports:
      - "5436:5434"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Comment
    volumes:
      - ./data/comment:/var/lib/postgresql/data
    networks:
      - my_network
  eurekaserver:
    image: anish1279/eurekaserver:v1
    ports:
      - "8761:8761"
    networks:
      - my_network

  auth-service:
    image: anish1279/auth:v2
    ports:
      - "9898:9898"
    depends_on:
      - eurekaserver
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/User
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - my_network

  blogs:
    image: anish1279/blog:v1
    ports:
      - "8090:8090"
    depends_on:
      - eurekaserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql2:5432/Blog
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - my_network

  user:
    image: anish1279/user:v1
    ports:
      - "8081:8080"
    depends_on:
      - eurekaserver
    networks:
      - my_network

  comment:
    image: anish1279/comment:v2
    ports:
      - "8084:8084"
    depends_on:
      - eurekaserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql3:5432/Comment
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - my_network

  api-gateway:
    image: anish1279/api-gateway:v2
    ports:
      - "9000:9000"
    depends_on:
      - eurekaserver
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
