apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: anish1279/comment:v2
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: comment-service
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql3:5432/Comment"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"

---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  selector:
    app: comment-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP