apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql3
  template:
    metadata:
      labels:
        app: postgresql3
    spec:
      containers:
        - name: postgresql3
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: POSTGRES_DB
              value: "Comment"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql3-storage
      volumes:
        - name: postgresql3-storage
          persistentVolumeClaim:
            claimName: postgresql3-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql3
spec:
  selector:
    app: postgresql3
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432