spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: User
          uri: lb://CODING-BLOCKS-INTERN
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: Blog
          uri: lb://BLOG
          predicates:
            - Path=/blogs/**
          filters:
            - AuthenticationFilter
        - id: Auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: Comment
          uri: lb://COMMENTS
          predicates:
            - Path=/comments/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
